### ISSUE TITLE
Question about LSApplicationQueriesSchemes

### ISSUE THREAD

**Issue by alistra** [mackuba/SafariAutoLoginTest#1]
Don't you have to add it in your Info.plist so your app can query the scheme and open it without prompting the user?

**Comment by mackuba** [comment]
The app is only receiving URLs with the custom scheme, the thing that opens them is technically the Safari component so it doesn't count as something that the app does. I.e. at no point in the app does it call `canOpenURL:` or `openURL:` with the custom scheme (or any scheme at all).
