### ISSUE TITLE
iOS 10 - SFSafariViewController blocking the UIWebView

### ISSUE THREAD

**Issue by oriharel** [mackuba/SafariAutoLoginTest#6]
Apparently doing 
`safari.view.alpha = 0.0;`
doesn't prevent the safari VC from blocking the web view in iOS10. any ideas how to overcome?

**Comment by oriharel** [comment]
the alpha setting actually blocks the SFSafariViewController from working in addition of blocking current context

**Comment by scottcc** [comment]
Seems as though a threshold of 0.05 for the alpha allows it to work again on iOS 10.
