### ISSUE TITLE
is this allowed or will the app be rejected?

### ISSUE THREAD

**Issue by haemi** [mackuba/SafariAutoLoginTest#7]
I don't know if  allows presenting SFSafariViewController invisible etc.

Does someone have more knowledge about this?

**Comment by mackuba** [comment]
Hmm, to be honest, I have no idea… I haven't actually tried it in any production app (there was an idea in the backlog, but there was never enough time ;).

I had reports that it doesn't even work at all in latest iOS, but I didn't have time to look into it either...

**Comment by jmartsch** [comment]
You can be sure it will be rejected because of the updated App Store Review Guidelines. See
http://stackoverflow.com/a/39494262

**Comment by mackuba** [comment]
Oh well… ¯\\\_(ツ)\_/¯ 

Thanks for the info!

**Comment by mackuba** [comment]
FYI, I've updated the readme with info about the current state, and I've added an alternative flow using `SFAuthenticationSession`.
